### PR TITLE
Updating docs and removing conflicting resource file

### PR DESCRIPTION
**Pull request by JaredBanyard**
The docs don't actually specify the Gradle or Maven artifact and there is an ic_launcher.png file that can cause conflicts if the developer has a file of the same name.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @JaredBanyard, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by JaredBanyard** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @JaredBanyard has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by JaredBanyard** [comment]
@doncung can you guys roll a new gradle/maven artifact version to get that ic_launcher.png file out of there?

**Pull request merged**
